name: CI

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'  # Укажите версию .NET 8

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Debug --no-restore

    - name: Run tests
      run: dotnet test --no-build --verbosity normal

    - name: Notify on failure
      if: ${{ failure() }}
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        author_name: CI Failure
        fields: repo,commit,author,action,workflow,job,took
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
